### ISSUE TITLE
Slowdown Alfred!

### ISSUE THREAD

**Issue by KhimairaCrypto** [PurpleBooth/alfred-emoji-snippet-pack#202]
I installed the snippets pack on my Mac Pro M1 32GB and it slowdown Alfred!

**Comment by PurpleBooth** [comment]
Oh, that's not ideal, I haven't noticed anything, let me have a think and see if there's a way I can prevent that.

**Comment by KhimairaCrypto** [comment]
Not sure If is because Alfred keeps all the snippets in memory, instead of loading them on demand and keep use the most recent/used ones in memory.
